name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

  workflow_dispatch:

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |

            echo "===== START DEPLOY ====="

            sudo systemctl start docker

            docker --version

            docker-compose --version

            echo "===== REMOVE OLD REPO ====="

            rm -rf ~/Three-tier-app-Action

            echo "===== CLONE REPOSITORY ====="

            git clone https://github.com/Abhi-Sangawade/Three-tier-app-Action.git ~/Three-tier-app-Action

            cd ~/Three-tier-app-Action

            echo "===== CREATE ENV FILE ====="

            cat > .env <<EOF
            DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
            MYSQL_ROOT_PASSWORD=root123
            DB_NAME=skillpulse
            DB_USER=skilluser
            DB_PASSWORD=skillpass
            EOF

            echo "===== FILES ====="

            ls -la

            echo "===== STARTING CONTAINERS ====="

            docker-compose up -d

            echo "===== RUNNING CONTAINERS ====="

            docker ps -a

            echo "===== CONTAINER LOGS ====="

            docker-compose logs --tail=50

            echo "===== END DEPLOY ====="
